version: "3.2"

volumes:
        sql:

services:
  sql:
        ports:
                - "1433:1433"
        environment:
                ACCEPT_EULA: Y
                SA_PASSWORD: Testing123
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: unless-stopped
        tty: true
        stdin_open: false
        volumes:
                - sql:/var/opt/mssql

  api:
        build:
            context: .
            dockerfile: TempLoggerService.Dashboard.Dockerfile
        ports:
                - "5000:80"
        environment:
            ConnectionStrings__Database: "Data Source=sql;Initial Catalog=TemperatureLog;User ID=sa;Password=Testing123;"
        image: templogger:api
        restart: unless-stopped
        tty: true
        stdin_open: false
        depends_on: sql

  dashboard:
        build:
            context: .
            dockerfile: TempLoggerService.Api.Dockerfile
        ports:
                - "5010:80"
        image: templogger:dashboard
        restart: unless-stopped
        tty: true
        stdin_open: false
