//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempLoggerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public device()
        {
            this.temperatures = new HashSet<temperature>();
        }
    
        public System.Guid deviceID { get; set; }
        public string deviceName { get; set; }
    
        public virtual ICollection<temperature> temperatures { get; set; }
    }
}
