//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempLoggerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public System.Guid eventID { get; set; }
        public string eventType { get; set; }
        public System.DateTime eventDate { get; set; }
        public string eventDetail { get; set; }
    }
}
