//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempLoggerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class temperature
    {
        public System.Guid deviceID { get; set; }
        public System.DateTime timestamp { get; set; }
        public decimal value { get; set; }
    
        public virtual device device { get; set; }
    }
}
